root: true
env:
  es2021: true
  node: true
extends:
  - "p5js"
parserOptions:
  ecmaVersion: 11
rules:
  "security/detect-non-literal-fs-filename": off
  "unicorn/prevent-abbreviations": off
  "no-process-exit": off
  "unicorn/no-process-exit": off
