# Generated by Django 4.0.3 on 2022-04-14 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import front_end.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('guesses', models.JSONField(default=front_end.models.default_json)),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gamer', 'game_id'],
            },
        ),
    ]
