# Generated by Django 4.0.3 on 2022-04-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['gamer', 'game_id'], 'verbose_name': 'Mastermind Game', 'verbose_name_plural': 'Mastermind Games'},
        ),
    ]
