# Generated by Django 4.0.3 on 2022-04-25 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front_end', '0002_alter_games_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('total_guesses', models.IntegerField(default=0)),
                ('avg_guesses', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('total_time', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('avg_time', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stats Model',
                'verbose_name_plural': 'Stats Models',
                'ordering': ['gamer', 'total_games'],
            },
        ),
    ]
