# Generated by Django 4.0.3 on 2022-04-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_remove_stats_id_alter_stats_gamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='avg_time',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='total_time',
        ),
    ]
