name: Docker Build CI

on:
  push:
    branches: [ main ]
    paths:
      - "mastermind_django_files/**"
      - "docker-compose.yaml"
      - "Dockerfile"
      - "entrypoint.sh"
  pull_request:
    branches: [ main ]
    paths:
      - "mastermind_django_files/**"
      - "docker-compose.yaml"
      - "Dockerfile"
      - "entrypoint.sh"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/chodges7/mastermind-capstone

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Generate tag
      id: tag
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.sha_short }},${{ env.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
