name: Docker Build CI

on:
  push:
    branches: [ main ]
    paths:
      - "mastermind_django_files/**"
      - "docker-compose.yaml"
      - "Dockerfile"
      - "entrypoint.sh"
  pull_request:
    branches: [ main ]
    paths:
      - "mastermind_django_files/**"
      - "docker-compose.yaml"
      - "Dockerfile"
      - "entrypoint.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with: 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mastermind-capstone:latest
