name: python-linter

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mastermind_django_files/static/game
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    outputs:
      score: ${{ steps.linter.outputs.score }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run linter
        id: linter
        run: eslint . --ext .js,.jsx,.ts,.tsx
        # working-directory: ${{ env.working-directory }}
