name: python-linter

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mastermind_django_files
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    outputs:
      score: ${{ steps.linter.outputs.score }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install dependancies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}

      - name: install pylint
        run: |
          pip install pylint==2.12 pylint-django==2.5
        working-directory: ${{ env.working-directory }}

      - name: run linter
        id: linter
        run: |
          pylint --load-plugins pylint_django --fail-under=5 --disable=missing-docstring --django-settings-module=mastermind.settings **/*.py > out.txt
          cat out.txt
          SCORE=`cat out.txt | grep -e '[0-9]*\.[0-9]*\/10' | cut -c 29-`
          echo "::set-output name=score::$SCORE"
        working-directory: ${{ env.working-directory }}

  badge:
    runs-on: ubuntu-latest
    needs: pylint

    steps: 
      - name: checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Make folder to hold badge
        id: folder
        run: |
          mkdir -p "${BADGE_PATH%/*}"
          echo "##[set-output name=path;]${BADGE_PATH}"
        env:
          BADGE_PATH: .github/badges/lint-score.svg
        
      - name: Badge Action
        uses: emibcn/badge-action@v1.2.4
        with:
          label: "Pylint score"
          status: ${{ needs.pylint.outputs.score }}
          color: 'pink'
          path: ${{ steps.folder.outputs.path }}

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: ${{ steps.folder.outputs.path }}
          if-no-files-found: error

      - name: Commit badge
        continue-on-error: true
        env:
          BADGE: ${{ steps.folder.outputs.path }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "docs: add/update badge"

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.folder.outputs.branch }}


