name: python-linter

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mastermind_django_files
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependancies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}

      - name: install pylint
        run: |
          pip install pylint pylint-django
        working-directory: ${{ env.working-directory }}

      - name: run linter
        run: |
          pylint --load-plugins pylint_django --disable=missing-docstring --output-format=json --output=pylint-out.json --django-settings-module=mastermind.settings **/*.py
        working-directory: ${{ env.working-directory }}

      - name: cat output
        run: |
          cat pylint-out.json
        working-directory: ${{ env.working-directory }}
