name: python-linter

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mastermind_django_files
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    outputs:
      score: ${{ steps.linter.outputs.score }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependancies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}
      - name: install pylint
        run: |
          pip install pylint pylint-django
        working-directory: ${{ env.working-directory }}
      - name: run linter
        id: linter
        run: |
          SCORE= `pylint --load-plugins pylint_django --disable=missing-docstring --django-settings-module=mastermind.settings **/*.py | grep -o '[0-9]*\.[0-9]+\/10'`
          echo "::set-output name=score::$SCORE"
        working-directory: ${{ env.working-directory }}

  badge:
    runs-on: ubuntu-latest
    needs: pylint

    steps: 
      - name: Badge Action
        uses: emibcn/badge-action@v1.2.4
        with:
          label: "Pylint score"
          status: ${{ needs.pylint.outputs.score }}
          color: '#f294ee'


